name: flutter_yuedu
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^5.0.2
  webview_flutter: ^0.3.9+1
#  flutter_webview_plugin: ^0.3.5
  flutter_swiper: ^1.1.6
  transparent_image: ^1.0.0
  cached_network_image: ^0.8.0
  flutter_splash_screen: ^0.1.0
  underline_indicator: ^0.0.2
  http: ^0.12.0+2
  provider: ^3.0.0+1
  oktoast: ^2.1.9
  package_info: ^0.4.0+4
  sqflite: ^1.1.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/update/ic_up_bg.png
    - images/update/ic_update_bg.png
    - images/update/ic_up_close.png
    - images/tabbar/tabbar_book.png
    - images/tabbar/tabbar_pressed_book.png
    - images/tabbar/tabbar_course.png
    - images/tabbar/tabbar_pressed_course.png
    - images/tabbar/tabbar_bookshelf.png
    - images/tabbar/tabbar_pressed_bookshelf.png
    - images/tabbar/tabbar_my.png
    - images/tabbar/tabbar_pressed_my.png
    - images/usercenter/usercenter_unlogin_header.png
    - images/usercenter/usercenter_wallet.png
    - images/usercenter/usercenter_membership.png
    - images/usercenter/usercenter_arrow.png
    - images/usercenter/icon_setting_medal.png
    - images/usercenter/usercenter_report.png
    - images/usercenter/usercenter_interest.png
    - images/usercenter/usercenter_card_header_boy.png
    - images/main/main_search.png
    - images/main/main_stage_arrow.png
    - images/main/btn_back_normal.png
    - images/main/parentveri_close.png
    - images/main/main_more_arrow.png
    - images/main/main_section_play.png
    - images/setting/icon_setting_cache.png
    - images/setting/icon_setting_push.png
    - images/setting/usercenter_feedback.png
    - images/setting/setting_about.png
    - images/setting/setting_update.png
    - images/setting/setting_version.png
    - images/setting/about_logo.png
    - images/bookshelf/bg_bookshelf_empty.png
    - images/login/login_header.png
    - images/login/login_tail.png
    - images/member/member_background.png
    - images/member/member_sales_sprite.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
